image: Visual Studio 2017
configuration: Release
install:
  - choco install gitversion.portable -y
before_build:
  - cmd: gitversion /l console /output buildserver /updateassemblyinfo
  - nuget restore
build:
  verbosity: minimal
  project: LessLinq.sln
after_build:
  - dotnet pack LessLinq -c %CONFIGURATION% /p:Version=%GitVersion_NuGetVersion% --no-build -o ..\artifacts
artifacts:
  - path: artifacts\*.*